# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-28 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useradmin', '0002_auto_20170311_1150'),
        ('authentication', '0005_auto_20170308_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfd_date', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('approval', models.NullBooleanField()),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='authentication.Profile')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useradmin.Medicine')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='authentication.Profile')),
            ],
        ),
    ]
