# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-30 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0002_auto_20170311_1150'),
        ('authentication', '0005_auto_20170308_2231'),
        ('activities', '0003_remove_order_mfd_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_trans', to='authentication.Profile')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useradmin.Medicine')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.Order')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_trans', to='authentication.Profile')),
            ],
        ),
    ]
