# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-08 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useradmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=30)),
                ('mfd_date', models.DateField(auto_now_add=True)),
                ('exp_date', models.DateField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('sold', models.IntegerField(default=0)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useradmin.Medicine')),
            ],
        ),
    ]
