# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-11 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20170308_2231'),
        ('usercompany', '0002_auto_20170309_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystock',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='authentication.Profile'),
            preserve_default=False,
        ),
    ]
