# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-11 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_auto_20170308_2231'),
        ('useradmin', '0002_auto_20170311_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_date', models.DateField(auto_now_add=True)),
                ('exp_date', models.DateField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('sold', models.IntegerField(default=0)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useradmin.Medicine')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Profile')),
            ],
            options={
                'db_table': 'shop_stock',
            },
        ),
    ]
