# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-11 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicine',
            table='medicine',
        ),
    ]
